### ISSUE TITLE
使用coco的预训练模型

### ISSUE THREAD

**Issue by vangoghcat** [zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5#20]
`- **预训练模型下载**
  - 使用mmdetection官方开源的casacde-rcnn-r50-fpn-2x的COCO预训练模型
  - 下载预训练模型后进行转换变为支持CFRCNN模型的预训练模型`
 coco的预训练模型是81类别的，而本数据是16类的，我看到对checkpoint文件转换也没有处理这个问题，那么预训练模型是怎么能成功加载的？
谢谢！

**Comment by zhengye1995** [comment]
In fact, in the process of loading the COCO pre-trained weight, the parameters with the same name but inconsistent dimensions will be ignored (not loaded), which means that the weights of the last FC layers in cls and reg branch are reinitialized.

You can also handle the final dimension yourself, but I don't think it is necessary, because there is no similarity between the cloth categories and the COCO categories.
