### ISSUE TITLE
求助 训练到最后有no such file or directory错误

### ISSUE THREAD

**Issue by YuzhouPeng** [zhengye1995/Tianchi-2019-Guangdong-Intelligent-identification-of-cloth-defects-rank5#5]
![捕获](https://user-images.githubusercontent.com/13601004/71427648-ca3c1680-26f5-11ea-838d-ce6d3e11ff0b.JPG)
我在train.sh里的设置：
![捕获1](https://user-images.githubusercontent.com/13601004/71427732-91507180-26f6-11ea-994c-0d10d880feb9.JPG)
求教为什么我无法保存权重，非常感谢

**Comment by zhengye1995** [comment]
1. The checkpoint named latest.pth has been saved in '../data/work_dirs/cascade_rcnn_r50_fpn_70e/latest.pth', you can find this file in this path due to your setting
2. This error is the publish_model.py can not find this file because your path my be wrong, you can try just run 'publish_model.py' with absolute path.
3. I just use publish_model.py to remove the optimizer's parameters to decrease the size of checkpoint.
Good luck and Merry Christmas！
